# -*- coding: utf-8 -*-
"""Deployment of Titanic Data set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtcnpmlVrH8ypN6XQXZFJJ0UXjK3HcZW
"""

import seaborn as sns
import pandas as pd
# Load Titanic dataset
titanic_df = sns.load_dataset('titanic')

# Preprocess the dataset (handle missing values, encode categorical variables, etc.)
# For simplicity, we'll drop rows with missing values and select a subset of features
titanic_df.dropna(inplace=True)
features = ['pclass', 'sex', 'age', 'fare', 'sibsp', 'parch']
X = titanic_df[features]
y = titanic_df['survived']

# Perform one-hot encoding for categorical variables (e.g., 'sex')
X = pd.get_dummies(X, columns=['sex'], drop_first=True)

X

from sklearn.model_selection import train_test_split

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

# Train a Random Forest classifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

# Make predictions on the test set
y_pred = model.predict(X_test)





